---
# tasks file for ansible-moinmoin-wsgi

- name: install libselinux-python, needed to manage SELinux contexts
  yum:
    name: libselinux-python
    state: latest

- name: install apache, mod_wsgi
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - mod_wsgi

- name: check for MoinMoin download
  stat:
    path: "/tmp/{{ moinmoin_src }}"
  register: moinsource

- name: download MoinMoin
  get_url:
    url: "{{ moinmoin_src_url }}"
    checksum: "{{ moinmoin_src_sha256 }}"
    dest: /tmp
    mode: 0440
  when: not moinsource.stat.exists or not moinsource.stat.isreg

- name: extract MoinMoin
  unarchive:
    src: "/tmp/{{ moinmoin_src }}"
    dest: "/tmp"

- name: run moinmoin setup script
  shell: "cd /tmp/{{ moinmoin_version }} && /usr/bin/python setup.py install"

- name: change ownership of moinmoin files
  file:
    path: "{{ item }}"
    recurse: yes
    owner: apache
    group: apache
  with_items:
    - "{{ moinmoin_default_path }}/data"
    - "{{ moinmoin_default_path }}/underlay"

- name: create moin directories
  file:
    path: "{{ moinmoin_install_path }}/{{ item }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755
  with_items:
    - data
    - underlay

- name: change SELinux file context to allow Apache to write data
  sefcontext:
    target: "{{ moinmoin_install_path }}/{{ item }}(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present
  with_items:
    - data
    - underlay

- name: run restorecon to apply the previous SELinux file context
  shell: "restorecon -R {{ moinmoin_install_path }}/{{ item }}"
  with_items:
    - data
    - underlay

- name: copy essential wiki files
  shell: "cp -R {{ moinmoin_default_path }}/{{ item }}/* {{ moinmoin_install_path }}/{{ item }}/ && chown -R apache:apache {{ moinmoin_install_path }}/{{ item }}"
  with_items:
    - data
    - underlay

- name: copy wiki config
  copy:
    src: wikiconfig.py
    dest: "{{ moinmoin_install_path }}/wikiconfig.py"
    owner: "apache"
    group: "apache"
    mode: 0644

- name: copy wiki wsgi
  copy:
    src: "{{ moinmoin_default_path }}/server/moin.wsgi"
    dest: "{{ moinmoin_install_path }}/moin.wsgi"
    remote_src: yes
    owner: "apache"
    group: "apache"
    mode: 0664

- name: update WSGI path
  lineinfile:
    path: "{{ moinmoin_install_path }}/moin.wsgi"
    regexp: "#sys.path.insert(0, '/path/to/wikiconfigdir')"
    line: "sys.path.insert(0, '/var/www/moin')"

- name: copy Apache conf script
  copy:
    src: moinmoin.conf
    dest: /etc/httpd/conf.d/moinmoin.conf
    owner: root
    group: root
    mode: 0644

- name: create an admin user
  shell: "/usr/bin/moin --config-dir={{ moinmoin_install_path }} account create --name={{ wiki_admin_username }} --password={{ wiki_admin_password }} --email={{ wiki_admin_email }}"

- name: remove Apache default welcome page
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent 

- name: allow ports 80, 443 via firewalld
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - http
    - https

- name: enable, start Apache
  systemd:
    name: httpd
    enabled: yes
    state: started
