---
# tasks file for ansible-moinmoin-wsgi

- name: install apache, mod_wsgi
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - mod_wsgi

- name: check for MoinMoin download
  stat:
    path: "/tmp/{{ moinmoin_src }}"
  register: moinsource

- name: download MoinMoin
  get_url:
    url: "{{ moinmoin_src_url }}"
    checksum: "{{ moinmoin_src_sha256 }}"
    dest: /tmp
    mode: 0440
  when: not moinsource.stat.exists or not moinsource.stat.isreg

- name: extract MoinMoin
  unarchive:
    src: "/tmp/{{ moinmoin_src }}"
    dest: "/tmp"

- name: run moinmoin setup script
  shell: "cd /tmp/{{ moinmoin_version }} && /usr/bin/python setup.py install"

- name: change ownership of moinmoin files
  file:
    path: "{{ item }}"
    recurse: yes
    owner: apache
    group: apache
  with_items:
    - /usr/share/moin/data
    - /usr/share/moin/underlay

- name: create moin directories
  file:
    path: "/var/www/moin/{{ item }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755
  with_items:
    - data
    - underlay

- name: change SELinux file context to allow Apache to write data
  sefcontext:
    target: "/var/www/moin/{{ item }}(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present
  with_items:
    - data
    - underlay

- name: run restorecon to apply the previous SELinux file context
  shell: "restorecon -R /var/www/moin/{{ item }}"
  with_items:
    - data
    - underlay

- name: copy essential wiki files
  shell: "cp -R /usr/share/moin/data/* /var/www/moin/data/ && chown -R apache:apache /var/www/moin/data"

- name: copy essential wiki files
  shell: "cp -R /usr/share/moin/underlay/* /var/www/moin/underlay/ && chown -R apache:apache /var/www/moin/underlay"

- name: copy wiki config
  copy:
    src: wikiconfig.py
    dest: /var/www/moin/wikiconfig.py
    owner: "apache"
    group: "apache"
    mode: 0644

- name: copy wiki wsgi
  copy:
    src: /usr/share/moin/server/moin.wsgi
    dest: /var/www/moin/moin.wsgi
    remote_src: yes
    owner: "apache"
    group: "apache"
    mode: 0664

- name: update WSGI path
  lineinfile:
    path: /var/www/moin/moin.wsgi
    regexp: "#sys.path.insert(0, '/path/to/wikiconfigdir')"
    line: "sys.path.insert(0, '/var/www/moin')"

- name: copy Apache conf script
  copy:
    src: moinmoin.conf
    dest: /etc/httpd/conf.d/moinmoin.conf
    owner: root
    group: root
    mode: 0644

- name: create an admin user
  shell: /usr/bin/moin --config-dir=/usr/share/moin account create --name=admin --password=admin --email=admin@localhost

- name: remove Apache default welcome page
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent 

- name: allow ports 80, 443 via firewalld
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - http
    - https

- name: enable, start Apache
  systemd:
    name: httpd
    enabled: yes
    state: started
