---
# tasks file for ansible-moinmoin-wsgi

- name: install apache, mod_wsgi
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - mod_wsgi

- name: download MoinMoin
  get_url:
    url: "{{ moinmoin_src_url }}"
    dest: /tmp
    mode: 0440

- name: extract MoinMoin
  unarchive:
    src: "/tmp/{{ moinmoin_src }}"
    dest: "/tmp"


- name: enable, start Apache
  systemd:
    name: httpd
    enabled: yes
    state: started
