---

- name: install SELinux packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - selinux-policy
    - libselinux-python
    - policycoreutils-python

- name: set SELinux to enforce policy
  selinux:
    policy: targeted
    state: enforcing

- name: enforce SELinux policy RIGHT NOW
  cmd: /usr/sbin/setenforce 1
 
...
